import cv2
img = cv2.imread(r'C:\tmp\PROJECTS\OpenCV_Python\in\lino21\9828253pvr.jpg')#, cv2.IMREAD_GRAYSCALE)
#cv2.imshow('Grayscale', gray_img)
#cv2.waitKey()
#cv2.imwrite('gray.jpg', gray_img)
if 0:
	yuv_img = cv2.cvtColor(img, cv2.COLOR_BGR2YUV)
	cv2.imshow('Y channel', yuv_img[:, :, 0])
	cv2.imshow('U channel', yuv_img[:, :, 1])
	cv2.imshow('V channel', yuv_img[:, :, 2])
	cv2.waitKey()
hsv_img = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)
cv2.imshow('HSV image', hsv_img)
#cv2.waitKey()
cv2.imshow('H channel', hsv_img[:, :, 0])
cv2.imshow('S channel', hsv_img[:, :, 1])
cv2.imshow('V channel', hsv_img[:, :, 2])
cv2.waitKey()
cv2.imwrite('hsv.jpg', hsv_img)
